### ISSUE TITLE
tty-clock feature parity

### ISSUE THREAD

**Issue by dpatterbee** [dpatterbee/tty-clock-go#16]
- [ ] Keybind clock movement #17 

- [ ] Screensaver mode #1 

- [ ] Show box #2 

- [x] Set clock colour #3 

- [ ] Use bold colours #4 

- [ ] Use UTC time #5 

- [ ] Display the clock on the specified terminal #6 

- [ ] Rebound the clock #7 

- [ ] Set date format #8 

- [ ] Don't quit on keypress #9 

- [ ] Show version #10 

- [ ] Show info #11 

- [ ] Show usage #12 

- [ ] Hide date #13 

- [ ] Enable blinking colon #14 

- [ ] Set custom delay #15
